[package]
name = "howmanysmall/janitor"
description = "A garbage collector object implementation for Roblox, featuring support for custom cleanup methods, Promises, and instance linking."
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.15.6"
exclude = [
	"docs",
	".moonwave",
	"test",
	"Packages",
	"Janitor.rbxm",
	"Janitor.rbxmx",
	"BuildJanitor.lua",
	"changelog.md",
	"README.md",
	".styluaignore",
	".gitignore",
	"foreman.toml",
	"Luau.toml",
	"moonwave.toml",
	"rotriever.toml",
	"selene.toml",
	"stylua.toml",
	"testez-companion.toml",
	"testez.toml",
]

[dependencies]
Promise = "evaera/promise@4.0.0-rc.2"
